faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "google"
  model_name: "models/embedding-001"

retriver:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "llama-3.1-8b-instant"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "AIzaSyAf3KHENEE13vprLMNMu0k5leW2lJIcDW8"
    temperature: 0
    max_output_tokens: 200
