faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "google"
  model_name: "models/embedding-001"

retriver:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "your_model_name"
    temperature: 0
    max_output_tokens: 2048
